# Generated by Django 4.1.4 on 2023-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categories_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_text',
            field=models.TextField(default=' ', max_length=300, verbose_name='Полное описание продукта(300 символов)'),
        ),
    ]
