# Generated by Django 4.1.4 on 2023-02-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=' ', max_length=300, verbose_name='Краткое описание продукта(300 символов)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_text',
            field=models.TextField(default=' ', verbose_name='Полное описание продукта'),
        ),
    ]
