# Generated by Django 4.1.4 on 2023-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_popular_product_product_of_the_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название темы')),
                ('image', models.ImageField(upload_to='photo/blog/%Y/%m/%d/', verbose_name='Фотография')),
                ('description', models.CharField(max_length=300, verbose_name='Подзаголовок(300 символов)')),
                ('full_text', models.TextField(verbose_name='Текст влога')),
                ('is_active', models.BooleanField(verbose_name='Опубликовано')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Отображение на главной странице(может быть кратное 4)'),
        ),
    ]
