# Generated by Django 4.1.4 on 2023-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blog_alter_product_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='photo/CategoriesBlog/%Y/%m/%d/', verbose_name='Фотография')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Категория влога',
                'verbose_name_plural': 'Категории влогов',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Влог', 'verbose_name_plural': 'Влоги'},
        ),
    ]
