# Generated by Django 4.1.4 on 2023-02-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categoriesblog_alter_blog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='CategoriesBlog',
        ),
    ]
