# Generated by Django 4.1.4 on 2023-02-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_blog_delete_categoriesblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='photo/CategoriesBlog/%Y/%m/%d/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Категория влога',
                'verbose_name_plural': 'Категории влогов',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название темы')),
                ('image', models.ImageField(upload_to='photo/blog/%Y/%m/%d/', verbose_name='Фотография')),
                ('description', models.CharField(max_length=300, verbose_name='Подзаголовок(300 символов)')),
                ('full_text', models.TextField(verbose_name='Текст влога')),
                ('is_active', models.BooleanField(verbose_name='Опубликовано')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categoriesblog', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Влог',
                'verbose_name_plural': 'Влоги',
            },
        ),
    ]
