# Generated by Django 4.1.4 on 2023-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_categoriesblog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярный влог'),
        ),
    ]
